### get请求获取授权码
GET {{auth_host}}/auth/oauth/authorize?client_id=XcWebApp&response_type=code&scope=all&redirect_uri=http://www.51xuecheng.cn


### POST申请令牌
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=5gfeWr&redirect_uri=http://www.51xuecheng.cn


### 密码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=stu1&password=111111

###校验jwt令牌
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2ODEzODk5MTEsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6IjNiZTE3MmI4LTEyNDEtNGM3NC04NmE0LTgzNDdmNzRkY2RiMCIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.RCKiNT8i9ltT1QOnYedpeA-QICLxUHM0dQ4w1yb-YgU
################扩展认证请求参数后######################
###密码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username={"username":"stu1","authType":"password","password":"111111"}
